GET http://localhost:3003/users


###

POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Turma Moreira",
    "email": "moreira@labenu.com",
    "password": "Labenu321"
}


###

POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "Casaco marrom",
    "price": 450.55,
    "image_url": "https://www.megashopsul.com.br/741-large_default/jaqueta-casaco-feminino-inverno-marrom.jpg"
}