GET http://localhost:3003/post/d4794239-5231-4734-a551-5c20dad036e1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjliNjRjOWI1LTQ1ZjAtNGZhMy1iMWQyLTg2ODZhYWY1YjUzNyIsImlhdCI6MTY1MTc1MjgwMSwiZXhwIjoxNjUxODM5MjAxfQ.We2WAgFxbdRFV8qQ7Pnllm8XT-u1g17NKQbBGzkb5mc


###
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Turma Moreira",
    "email": "moreira@labenu.com",
    "password": "senha123"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "moreira@labenu.com",
    "password": "senha123"
}


###
POST http://localhost:3003/post/create
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjliNjRjOWI1LTQ1ZjAtNGZhMy1iMWQyLTg2ODZhYWY1YjUzNyIsImlhdCI6MTY1MTc1MjgwMSwiZXhwIjoxNjUxODM5MjAxfQ.We2WAgFxbdRFV8qQ7Pnllm8XT-u1g17NKQbBGzkb5mc
Content-Type: application/json

{
    "photo": "https://img.freepik.com/fotos-gratis/quadro-negro-com-livro-de-pilha_488220-9873.jpg?w=2000",
    "description": "Ler é viajar sem sair do lugar",
    "type": "normal"
}

