### EXERCÍCIO 1   
POST http://localhost:3003/user
Content-Type: application/json

{
    "name": "Dev Tester",
    "nickname": "Dev",
    "email": "dev@tester.com"
}


### EXERCÍCIO 2 
GET http://localhost:3003/user/1
Content-Type: application/json


### EXERCÍCIO 3 
PUT http://localhost:3003/user/edit/2
Content-Type: application/json

{
    "name": "Leandro Karnal",
    "nickname": "Leandro"
}


### EXERCÍCIO 4  
POST http://localhost:3003/task
Content-Type: application/json

{
    "title": "Revisar TS",
	"description": "Revisar para fixar.",
	"limitDate": "20/04/2022",
	"creatorUserId": "10"
}


### EXERCÍCIOS 5 E 11
GET http://localhost:3003/task/1
Content-Type: application/json


### EXERCÍCIO 6
GET http://localhost:3003/user/all
Content-Type: application/json


### EXERCÍCIO 7
GET http://localhost:3003/task?creatorUserId=1
Content-Type: application/json


### EXERCÍCIO 8
GET http://localhost:3003/user?query=di
Content-Type: application/json


### EXERCÍCIOS 9 E 16
POST http://localhost:3003/task/responsible
Content-Type: application/json

{
    "taskId": "10",
    "responsibleUserId": ["10", "1"]
}


### EXERCÍCIO 10 
GET http://localhost:3003/task/4/responsible
Content-Type: application/json


### EXERCÍCIO 12 
PUT http://localhost:3003/task/status/5
Content-Type: application/json

{
    "status": "to_do"
}


### EXERCÍCIO 13 
GET http://localhost:3003/task/all?status=to_do
Content-Type: application/json


### EXERCÍCIO 14
GET http://localhost:3003/task/delayed
Content-Type: application/json


### EXERCÍCIO 15
DELETE http://localhost:3003/task/2/responsible/1
Content-Type: application/json


### EXERCÍCIO 17
GET http://localhost:3003/task/name?query=es
Content-Type: application/json


### EXERCÍCIO 19
DELETE http://localhost:3003/task/5
Content-Type: application/json


### EXERCÍCIO 20
DELETE http://localhost:3003/user/10
Content-Type: application/json