GET http://localhost:3003/users
Content-Type: application/json

###
GET http://localhost:3003/search/types/?type=admi
Content-Type: application/json

###
GET http://localhost:3003/search/name/?name=diego
Content-Type: application/json

###
POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "d",
    "email": "anna@moreira.com",
    "type": "admin",
    "age": 31
}
