GET http://localhost:3003/users
Content-Type: application/json


###
GET http://localhost:3003/statement?cpf=636.157.687-60
Content-Type: application/json


###
POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Diego Conte",
    "CPF": "859.894.340-14",
    "birthDate": "03/04/2004"
}


###
POST http://localhost:3003/pay
Content-Type: application/json

{
    "CPF": "636.157.687-60",
    "amount": 5100,
    "date": "04/04/2022",
    "description": "Buying new car."
}


###
POST http://localhost:3003/transfer
Content-Type: application/json

{
    "sourceName": "Ana Paula Arósio",
    "sourceCPF": "636.157.687-60",
    "targetName": "William Bonemer Júnior",
    "targetCPF": "097.956.522-73",
    "amount": 10
}


###
PUT http://localhost:3003/deposit
Content-Type: application/json

{
    "name": "Ana Paula Arósio",
    "CPF": "636.157.687-60",
    "amount": -40
}


###
PUT http://localhost:3003/balance/?cpf=636.157.687-60
Content-Type: application/json